USERNAME = "example@email.com"
PASSWORD = "faedasfds"
URL = "https://www.skooldio.com"
LOGIN_URL = "https://www.skooldio.com/login"
MAIN_PAGE_URL = "https://www.skooldio.com/"
COURSE_PAGE_URL = "https://www.skooldio.com/browse?type=COURSE"
COURSE_CATEGORY_PREFIX = "https://www.skooldio.com/browse?type=COURSE&category="